List<String> countrycode = [
  "ae",
  "ar",
  "at",
  "au",
  "be",
  "bg",
  "br",
  "ca",
  "ch",
  "cn",
  "co",
  "cu",
  "cz",
  "de",
  "eg",
  "fr",
  "gb",
  "gr",
  "hk",
  "hu",
  "id",
  "ie",
  "il",
  "in",
  "it",
  "jp",
  "kr",
  "lt",
  "lv",
  "ma",
  "mx",
  "my",
  "ng",
  "nl",
  "no",
  "nz",
  "ph",
  "pl",
  "pt",
  "ro",
  "rs",
  "ru",
  "sa",
  "se",
  "sg",
  "si",
  "sk",
  "th",
  "tr",
  "tw",
  "ua",
  "us",
  "ve",
  "za"
];

List<String> country = [
  "United Arab Emirates",
  "Argentina",
  "Austria",
  "Australia",
  "Belgium",
  "Bulgaria",
  "Brazil",
  "Canada",
  "Switzerland",
  "China",
  "Colombia",
  "Cuba",
  "Czechia",
  "Germany",
  "Egypt",
  "France",
  "Great Britian",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Indonesia",
  "Ireland",
  "Israel",
  "India",
  "Italy",
  "Japan",
  "Korea Republic",
  "Lithuania",
  "Latvia",
  "Morocco",
  "Mexico",
  "Malaysia",
  "Nigeria",
  "Netherlands",
  "Norway",
  "New Zealand",
  "philippines",
  "Poland",
  "Portgal",
  "Romania",
  "Serbia",
  "Russia",
  "Saudi Arabia",
  "Sweden",
  "Singapore",
  "Slovenia",
  "Slovakia",
  "Thailand",
  "Turkiye",
  "Taiwan",
  "Ukraine",
  "United States",
  "Venezuela",
  "South Africa"
];

// Map<String, String> country = {
//   "United Arab Emirates": "ae",
//   "Argentina": "ar",
//   "Austria": "at",
//   "Australia": "au",
//   "Belgium": "be",
//   "Bulgaria": "bg",
//   "Brazil": "br",
//   "Canada": "ca",
//   "Switzerland": "ch",
//   "China": "cn",
//   "Colombia": "co",
//   "Cuba": "cu",
//   "Czechia": "cz",
//   "Germany": "de",
//   "Egypt": "eg",
//   "France": "fr",
//   "Great Britian": "gb",
//   "Greece": "gr",
//   "Hong Kong": "hk",
//   "Hungary": "hu",
//   "Indonesia": "id",
//   "Ireland": "ie",
//   "Israel": "il",
//   "India": "in",
//   "Italy": "it",
//   "Japan": "jp",
//   "Korea Republic": "kr",
//   "Lithuania": "lt",
//   "Latvia": "lv",
//   "Morocco": "ma",
//   "Mexico": "mx",
//   "Malaysia": "my",
//   "Nigeria": "ng",
//   "Netherlands": "nl",
//   "Norway": "no",
//   "New Zealand": "nz",
//   "philippines": "ph",
//   "Poland": "pl",
//   "Portgal": "pt",
//   "Romania": "ro",
//   "Serbia": "rs",
//   "Russia": "ru",
//   "Saudi Arabia": "sa",
//   "Sweden": "se",
//   "Singapore": "sg",
//   "Slovenia": "si",
//   "Slovakia": "sk",
//   "Thailand": "th",
//   "Turkiye": "tr",
//   "Taiwan": "tw",
//   "Ukraine": "ua",
//   "United States": "us",
//   "Venezuela": "ve",
//   "South Africa": "za"
// };
